### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by pangfumin** [ethz-ait/duo_vio#1]
HI，
Thank you for your great work and sharing the code !The result video is impressive.
Can you give some access accessible datasets, cause we do not have the duo3d camera?
I will  deeply appreciate it if you can help.

Best.

**Comment by tnaegeli** [comment]
Hi,
We will provide asap. a rosbag with a callibration and groundtruth. 
I hope this helps.

Best,

**Comment by tnaegeli** [comment]
Hi all,
We recorded 2 datasets with the camera as Rosbags:
ait.inf.ethz.ch/projects/2016/duo-vio/downloads/DUOVioData.zip

best,
Tobi
