### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by jasonwurzel** [ethz-ait/duo_vio#2]
Hi, 
First of all, thank you for your publication and the open source code. Interesting work! I'm trying to get duo_vio running stable and precise, but I'm having some difficulties. Here are some questions I have:

- When running DUOCalibrator, there is the parameter "Checkerboard dimensions". What does it mean? is it the length of a single square, or the width, or height of the whole board?

- In the cameraParams.yaml, could you explain the parameters R_ci, R_lr, R_rl, r_lr, t_ci?
My guess for R_ci is the rotation matrix of world to imu?

Thank you!

**Comment by ndepal** [comment]
Hi Jason

* "Checkerboard dimensions" is the length of each checkerboard square in units of mm
* The parameters are as follows
    * `R_ci`: Rotation matrix from IMU to (left) camera frame
    * `R_lr`: Rotation matrix from right to left camera frame
    * `R_rl`: Transpose of `R_lr`
    * `r_lr`: Translation between left and right camera frame
    * `t_ci`: Translation between camera and IMU frame

I hope that helps.

**Comment by jasonwurzel** [comment]
Hi, 

thank you for your answers! (that explains why my calibration kept failing ;-) )
