### ISSUE TITLE
Camera and IMU sampling rates

### ISSUE THREAD

**Issue by ghost** [ethz-ait/duo_vio#7]
Hi, thanks for making the code available. I am trying to run `duo3d_short.bag`. There are 2416 and 2415 messages for IMU and camera, so I assume that the sampling rates for IMU and camera are almost the same. However, if I print the received `ait_ros_messages::VioSensorMsg`, it shows that `msg.imu.size()` is always greater than 1. For instance, `(sec, nsec, accel_x, accel_y, accel_z, gyro_x, gyro_y, gyro_z)` for the first `ait_ros_messages::VioSensorMsg` is
`0 0 0.0520 -9.7860 -2.6441 -0.0548 -0.0787 0.0234`
`0 0 0.0479 -9.8760 -2.6105 -0.0585 -0.0798 0.0250`
`0 0 0.1197 -9.7620 -2.6728 -0.0580 -0.0776 0.0234`
`0 0 0.0718 -9.7860 -2.6920 -0.0601 -0.0787 0.0207`
In contrast, the corresponding `(sec, nsec, accel_x, accel_y, accel_z, gyro_x, gyro_y, gyro_z)` from `duo3d_short.bag` is only
`0 0 0.0718 -9.7860 -2.6920 -0.0601 -0.0787 0.0207`
I am wondering where are the messages other than the last line coming from?

**Comment by ndepal** [comment]
The DUO3d camera provides multiple IMU samples for each image pair sample. These IMU samples are published in a [VioSensorMsg](https://github.com/ethz-ait/ait_ros_messages/blob/master/msg/VioSensorMsg.msg) together with the images.
What are you looking at when you say the data from `duo3d_short.bag` only has one IMU entry?
