### ISSUE TITLE
ROS data sets not available

### ISSUE THREAD

**Issue by shening** [ethz-ait/duo_vio#9]
Hi 

Does anyone still have the sample ROS bag files . The link provided does not work anymore 

Thank you

Sebastian

**Comment by yuweijheng** [comment]
[https://ait.ethz.ch/projects/2016/duo-vio/downloads/DUOVioData.zip](url)

**Comment by ndepal** [comment]
The link in the readme should be fixed.
Please reopen this issue if you still can't download the dataset.
